export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const FOCUS_AIRPLANE_PENDING = 'FOCUS_AIRPLANE_PENDING';
export const FOCUS_AIRPLANE_SUCCESS = 'FOCUS_AIRPLANE_SUCCESS';
export const FOCUS_AIRPLANE_ERROR = 'FOCUS_AIRPLANE_ERROR';
export const UNFOCUS_AIRPLANE = 'UNFOCUS_AIRPLANE';


export const FETCH_ALL_DATA_SUCCESS = 'FETCH_ALL_DATA_SUCCESS';
export const FETCH_ALL_DATA_ERROR = 'FETCH_ALL_DATA_ERROR';
export const FETCH_ALL_DATA_PENDING = 'FETCH_ALL_DATA_PENDING';

export const TOGGLE_FIRS = 'TOGGLE_FIRS';
export const TOGGLE_COLOR_MODE = 'TOGGLE_COLOR_MODE';
export const TOGGLE_AIRPORT_MARKER = 'TOGGLE_AIRPORT_MARKER';
export const TOGGLE_AIRPORT_MARKER_ATC_BADGES = 'TOGGLE_AIRPORT_MARKER_ATC_BADGES';
export const TOGGLE_AIRPORT_MARKER_APPROACH_CIRCLE = 'TOGGLE_AIRPORT_MARKER_APPROACH_CIRCLE';